
---Various commands for interacting with compute pools & services in SQL, follow
SHOW COMPUTE POOLS;

ALTER COMPUTE POOL CONTAINER_HOL_POOL RESUME;

SHOW SERVICES;
-- need to set database first to see related services

USE DATABASE LLMDEMO;
SHOW SERVICES;

USE DATABASE CONTAINER_HOL_DB;

 USE ROLE CONTAINER_USER_ROLE;

CALL SYSTEM$REGISTRY_LIST_IMAGES('/CONTAINER_HOL_DB/PUBLIC/IMAGE_REPO');

CREATE SERVICE CONTAINER_HOL_DB.PUBLIC.CODE_SERVER
IN COMPUTE POOL CONTAINER_HOL_POOL
from @specs
specification_file='code-server.yaml'
external_access_integrations = (ALLOW_ALL_EAI);


DESCRIBE SERVICE code_server;

SHOW SERVICES;

CALL SYSTEM$GET_SERVICE_STATUS('CONTAINER_HOL_DB.PUBLIC.CODE_SERVER_2');
CALL SYSTEM$GET_SERVICE_LOGS('CONTAINER_HOL_DB.PUBLIC.CODE_SERVER_2', '0', 'code-server-2',100);

SHOW ENDPOINTS IN SERVICE CODE_SERVER;


---8/13 updates - with conda

ALTER COMPUTE POOL CONTAINER_HOL_POOL SET MAX_NODES = 2;

CREATE SERVICE CONTAINER_HOL_DB.PUBLIC.CODE_SERVER_2
IN COMPUTE POOL CONTAINER_HOL_POOL
from @specs
specification_file='code-server-2.yaml'
external_access_integrations = (ALLOW_ALL_EAI);

SHOW SERVICES;

CALL SYSTEM$GET_SERVICE_LOGS('CONTAINER_HOL_DB.PUBLIC.CODE_SERVER_2', '0', 'code-server-2',100);

ALTER SERVICE CODE_SERVER_2 SUSPEND;

ALTER SERVICE code_server_2
FROM @specs
SPECIFICATION_FILE='code-server-2.yaml';

ALTER SERVICE CODE_SERVER_2 RESUME;

SHOW SERVICES;

SHOW ENDPOINTS IN SERVICE CODE_SERVER_2;

#DROP SERVICE CODE_SERVER_2;




----Demo

CREATE SERVICE CONTAINER_HOL_DB.PUBLIC.CODE_SERVER_3
IN COMPUTE POOL CONTAINER_HOL_POOL
from @specs
specification_file='code-server-2.yaml'
external_access_integrations = (ALLOW_ALL_EAI);

CALL SYSTEM$GET_SERVICE_STATUS('CONTAINER_HOL_DB.PUBLIC.CODE_SERVER_3');
